export const PLANS = {
  PRO: "pro",
  FREE: "free",
  ULTRA: "ultra",
};

export const planDetails = [
  {
    name: "Basic",
    id: "free",
    description: "Perfecto para emprendedores y pequeños negocios",
    price: "Gratis",
    period: "",
    features: [
      { name: "Hasta 100 productos", included: true },
      { name: "Control básico de inventario", included: true },
      { name: "1 usuario", included: true },
      { name: "Reportes básicos", included: true },
      { name: "Soporte por email", included: true },
      { name: "API Access", included: false },
      { name: "Integraciones", included: false },
      { name: "Soporte 24/7", included: false },
    ],
    buttonText: "Comenzar gratis",
    buttonLink: "/dashboard",
    highlighted: false,
  },
  {
    name: "Professional",
    id: "pro",
    description: "Ideal para negocios en crecimiento",
    price: "COP $150,000.00",
    period: "/mes",
    features: [
      { name: "Productos ilimitados", included: true },
      { name: "Control avanzado de inventario", included: true },
      { name: "Hasta 5 usuarios", included: true },
      { name: "Reportes avanzados", included: true },
      { name: "Soporte prioritario", included: true },
      { name: "API Access", included: true },
      { name: "Integraciones básicas", included: true },
      { name: "Soporte 24/7", included: false },
    ],
    buttonText: "Comenzar",
    buttonLink: "/register?plan=pro",
    highlighted: true,
  },
  {
    name: "Enterprise",
    id: "ultra",
    description: "Para grandes empresas con necesidades específicas",
    price: "COP $385,000.00",
    period: "/mes",
    features: [
      { name: "Todo lo de Professional", included: true },
      { name: "Usuarios ilimitados", included: true },
      { name: "API personalizada", included: true },
      { name: "Integraciones avanzadas", included: true },
      { name: "Soporte 24/7", included: true },
      { name: "Capacitación personalizada", included: true },
      { name: "SLA garantizado", included: true },
      { name: "Ambiente de pruebas", included: true },
    ],
    buttonText: "Comenzar",
    buttonLink: "/contact",
    highlighted: false,
  },
];